project:
  type: website

website:
  title: "Airport for DuckDB"
  site-url: https://airport.query.farm
  repo-url: https://github.com/Query-farm/airport-docs
  repo-branch: master
  repo-actions: [edit, source, issue]
  google-analytics: "G-NQTYGWQD1B"
  cookie-consent: true
  favicon: farm-icon.png
  open-graph: true
  twitter-card:
    image: farm-icon.png

  page-footer:
    left: |
      &copy; 2025 <a href="https://query.farm">query.farm</a>
    right: |
      Built for: <a href="https://duckdb.org"><img src="https://duckdb.org/images/logo-dl/DuckDB_Logo-horizontal.png" style="height: 2em; padding-right: 2em;" alt="DuckDB Logo"/></a>
      Made in: <a href="https://www.miami.gov/Home"><img src="https://upload.wikimedia.org/wikipedia/commons/8/86/City_of_Miami_Primary.svg" height="40px"/></a>
      <a href="https://www.charlottesville.gov"><img src="https://www.charlottesville.gov/ImageRepository/Document?documentID=10798" height="40px"/></a>
      <a href="https://europa.eu"><img src="https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg" height="40px"/></a>
  announcement:
    icon: info-circle
    dismissable: true
    content: "This is a pre-release documentation and is subject to change. Airport will be released after DuckDB 1.3.0 is released."
    type: info
    position: below-navbar
  navbar:
    search: true
    pinned: true
    right:
      - icon: github
        href: https://github.com/Query-farm/duckdb-airport-extension
        aria-label: GitHub
    left:
      - href: index.qmd
        text: Home
      - text: Features
        href: features.qmd
      - text: "Why use Airport?"
        menu:
          - text: "Why Airport Exists"
            href: motivation.qmd
          - text: "Airport as part of Data-as-a-Service"
            href: data_as_a_service.qmd
          - text: "Rethinking Data Strategy"
            href: rethinking_data_strategy_airport_extension.qmd

  sidebar:
      style: "docked"
      contents:
        - text: "Extension API"
          href: api.qmd
        - text: "---"
        - text: "Catalog Integration"
          href: catalog_integration.qmd
          contents:
            - section: "Schemas"
              contents:
                - text: "Create"
                  href: schema_create.qmd
                - text: "Drop"
                  href: schema_drop.qmd
            - section: "Tables"
              href: tables.qmd
              contents:
                - text: "Select"
                  href: table_select.qmd
                - text: "Insert"
                  href: table_insert.qmd
                - text: "Update"
                  href: table_update.qmd
                - text: "Delete"
                  href: table_delete.qmd
                - text: "Create"
                  href: table_create.qmd
                - text: "Drop"
                  href: table_drop.qmd
                - text: "Alter"
                  hre f: table_alter.qmd
                - text: "RowId Pseudocolumn"
                  href: table_row_ids.qmd
                - text: "Column Statistics"
                  href: table_column_statistics.qmd
                - text: "Constraints, Checks, Default Values"
                  href: table_constraints.qmd
                - text: "Transactions"
                  href: transactions.qmd
            - text: "Scalar Functions"
              href: scalar_functions.qmd
            - text: "Table Returning Functions"
              href: table_returning_functions.qmd
            - text: "Versioning"
              href: catalog_current_version.qmd
        - text: "---"
        - section: "Server Development"
          contents:
              - text: "Basics"
                href: server_basics.qmd
              - text: "Catalog Integration"
                href: server_catalog_integration.qmd
              - text: "Predicate Pushdown"
                href: server_predicate_pushdown.qmd
              - text: "Authentication"
                href: request_authentication.qmd
              - text: "Row and Column Level Filtering"
                href: server_row_and_column_filtering.qmd
              - text: "Time Travel"
                href: server_time_travel.qmd
              - text: "Client Versioning"
                href: server_client_versioning.qmd
              - text: "Data Types"
                href: server_data_types.qmd
              - text: "Request Headers"
                href: standard_headers.qmd
              - section: "RPC Actions"
                href: server_actions.qmd
                contents:
                  - text: "add_column"
                    href: server_action_add_column.qmd
                  - text: "add_constraint"
                    href: server_action_add_constraint.qmd
                  - text: "add_field"
                    href: server_action_add_field.qmd
                  - text: "catalog_version"
                    href: server_action_catalog_version.qmd
                  - text: "change_column_type"
                    href: server_action_change_column_type.qmd
                  - text: "column_statistics"
                    href: server_action_column_statistics.qmd
                  - text: "create_schema"
                    href: server_action_create_schema.qmd
                  - text: "create_table"
                    href: server_action_create_table.qmd
                  - text: "create_transaction"
                    href: server_action_create_transaction.qmd
                  - text: "drop_not_null"
                    href: server_action_drop_not_null.qmd
                  - text: "drop_schema"
                    href: server_action_drop_schema.qmd
                  - text: "drop_table"
                    href: server_action_drop_table.qmd
                  - text: "endpoints"
                    href: server_action_endpoints.qmd
                  - text: "flight_info"
                    href: server_action_flight_info.qmd
                  - text: "list_schemas"
                    href: server_action_list_schemas.qmd
                  - text: "remove_column"
                    href: server_action_remove_column.qmd
                  - text: "remove_field"
                    href: server_action_remove_field.qmd
                  - text: "rename_column"
                    href: server_action_rename_column.qmd
                  - text: "rename_field"
                    href: server_action_rename_field.qmd
                  - text: "rename_table"
                    href: server_action_rename_table.qmd
                  - text: "set_default"
                    href: server_action_set_default.qmd
                  - text: "set_not_null"
                    href: server_action_set_not_null.qmd
                  - text: "table_function_flight_info"
                    href: server_action_table_function_flight_info.qmd
        - text: "---"
        - text: "FAQ"
          href: faq.qmd
        - text: "---"

format:
  html:
    theme: [zephyr, theme.scss]
    mainfont: Roboto,Open Sans, Helvetica
    css: styles.css
    toc: true



