---
title: "Alter"
---

The Airport extension supports altering tables. The Arrow Flight server can decide if the alteration should be applied..

## Example

For a DuckDB session to alter a table, a standard SQL `ALTER TABLE` statement is executed in a schema that is managed by the Airport extension.

```sql
-- Attach an Airport database
ATTACH 'example' (TYPE AIRPORT, location 'grpc://localhost:50312/');

-- assume that there is a `main` schema
-- already in the `example` database
CREATE TABLE example.main.employees (
  name varchar,
  id integer
);

ALTER TABLE example.main.employees DROP COLUMN id;
```

## Arrow Flight Server Implementation Notes

The Airport extension will perform a `DoAction` Arrow Flight RPC with a method name that corresponds to the type of alteration being performed.

The types of alterations that can be performed are:

| Action Name | Description |
|-------------|-------------|
| [`add_column`](server_action_add_column.qmd "Add a column to a table") | Add a column to a table. |
| [`add_constraint`](server_action_add_constraint.qmd "Add a constraint to a field") | Add a constraint to a field. |
| [`add_field`](server_action_add_field.qmd "Add a field to a structure") | Add a field to a structure. |
| [`change_column_type`](server_action_change_column_type.qmd "Change the type of a column") | Change the type of a column. |
| [`drop_not_null`](server_action_drop_not_null.qmd "Drop NOT NULL constraint from a field") | Drop NOT NULL constraint from a field. |
| [`remove_column`](server_action_remove_column.qmd "Remove a column from a table") | Remove a column from a table. |
| [`remove_field`](server_action_remove_field.qmd "Remove a field from a structure") | Remove a field from a structure. |
| [`rename_column`](server_action_rename_column.qmd "Rename a column") | Rename a column. |
| [`rename_field`](server_action_rename_field.qmd "Rename a field in a structure") | Rename a field in a structure. |
| [`rename_table`](server_action_rename_table.qmd "Rename a table") | Rename a table. |
| [`set_default`](server_action_set_default.qmd "Set a default value for a field") | Set a default value for a field. |
| [`set_not_null`](server_action_set_not_null.qmd "Set a field to NOT NULL") | Set a field to NOT NULL. |

Each type of alteration takes a different parameter structure.

All actions are presumed not to return a value, but should raise an exception upon error.
